attach VideoDecoder to depacketizer instead of source
medooze/video-codecs-node pull request #9
Opened 2024-03-20 20:18 UTC by mildsunrise

JS-side of the changes in https://github.com/medooze/media-server/pull/271.

instead of exposing a SetIncoming() method to JS, we expose a toMediaFrameListener() that JS can then attach and detach to the depacketizer directly. this is simpler and consistent with what we do elsewhere (such as in the recorder)

2024-03-21 08:12 UTC, murillo128 requested changes
rename .i file, otherwise lgtm

2024-03-21 08:12 UTC, murillo128 commented on lib/VideoDecoder.js
> +			track.AddMediaListener(this.decoder.toMediaFrameListener());
```suggestion
			track.depacketizer.AddMediaListener(this.decoder.toMediaFrameListener());
```

2024-03-21 21:58 UTC, mildsunrise commented
yes, I didn't do the rename yet to facilitate review. did it now.

2024-05-31 02:08 UTC, harryz2000 commented on lib/VideoDecoder.js
> +			this.attached.depacketizer.RemoveMediaListener(this.decoder.toMediaFrameListener());
Seems indent was not right.

2024-05-31 02:10 UTC, harryz2000 commented
lgtm

2024-05-31 02:27 UTC, merged